const produse = [
  {
    id: 1,
    nume: "Chitară Acustică Yamaha F310",
    categorie: "chitari",
    pret: 750,
    pretRedus: null,
    rating: 4.5,
    imagine: "https://images.unsplash.com/photo-1510915361894-db8b60106cb1?w=400&h=400&fit=crop",
    descriereScurta: "Chitară acustică perfectă pentru începători și intermediari.",
    descriereLunga: "Yamaha F310 este una dintre cele mai populare chitări acustice pentru începători. Corpul din lemn de abache oferă un sunet cald și echilibrat, gâtul din meranti asigură confort la cântare, iar coardele din oțel inoxidabil rezistă în timp. Livrată cu husa de protecție.",
    stoc: 15,
    popular: true
  },
  {
    id: 2,
    nume: "Chitară Electrică Fender Stratocaster",
    categorie: "chitari",
    pret: 3200,
    pretRedus: 2800,
    rating: 4.8,
    imagine: "https://images.unsplash.com/photo-1564186763535-ebb21ef5277f?w=400&h=400&fit=crop",
    descriereScurta: "Legendara Stratocaster – sunet iconic, calitate superioară.",
    descriereLunga: "Fender Stratocaster este chitara care a definit rock-ul modern. Cu 3 pickup-uri single coil, bridge tremolo și corp din arin, oferă un sunet versatil de la blues la rock și jazz. Gâtul din arțar cu tastieră din paducel asigură o cântare fluidă și plăcută.",
    stoc: 8,
    popular: true
  },
  {
    id: 3,
    nume: "Pian Digital Yamaha P-45",
    categorie: "piane",
    pret: 2200,
    pretRedus: null,
    rating: 4.7,
    imagine: "https://images.unsplash.com/photo-1520523839897-bd0b52f945a0?w=400&h=400&fit=crop",
    descriereScurta: "Pian digital compact cu 88 clape ponderate – sunet autentic.",
    descriereLunga: "Yamaha P-45 reproduces the feel and sound of an acoustic piano with 88 weighted keys and Advanced Wave Memory technology. Perfect for students and professionals alike. Includes sustain pedal, music stand, and power adapter. Slim design fits any room.",
    stoc: 5,
    popular: true
  },
  {
    id: 4,
    nume: "Set Tobe Complet Tama Imperialstar",
    categorie: "tobe",
    pret: 3800,
    pretRedus: 3200,
    rating: 4.6,
    imagine: "https://images.unsplash.com/photo-1519892300165-cb5542fb47c7?w=400&h=400&fit=crop",
    descriereScurta: "Set de tobe profesional – 5 piese, finisaj premium.",
    descriereLunga: "Tama Imperialstar este setul perfect pentru bateristul serios. Include bass drum 22\", snare drum 14\", 3 tom-uri și suporți hardware de calitate. Carcasele din lemn de tei oferă un sunet cald și profund. Ideal pentru repetiții și concerte.",
    stoc: 3,
    popular: false
  },
  {
    id: 5,
    nume: "Flaut Dulce Soprano",
    categorie: "vanturi",
    pret: 120,
    pretRedus: null,
    rating: 4.2,
    imagine: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&h=400&fit=crop",
    descriereScurta: "Flaut dulce din plastic ABS – ideal pentru copii și începători.",
    descriereLunga: "Flautul dulce soprano este instrumentul ideal pentru primele lecții de muzică. Fabricat din plastic ABS de înaltă calitate, produce un sunet clar și plăcut. Ușor de curățat și întreținut. Include husă de protecție și instrucțiuni pentru începători.",
    stoc: 50,
    popular: false
  },
  {
    id: 6,
    nume: "Saxofon Alto Yamaha YAS-280",
    categorie: "vanturi",
    pret: 2800,
    pretRedus: null,
    rating: 4.4,
    imagine: "https://images.unsplash.com/photo-1415201364774-f6f0bb35f28f?w=400&h=400&fit=crop",
    descriereScurta: "Saxofon alto profesional – sunet bogat și intonație precisă.",
    descriereLunga: "Yamaha YAS-280 este saxofonul ideal pentru studenti și muzicieni intermediari. Corpul din alamă lacuită auriu oferă un sunet cald și puternic. Mecanica fluentă și intonația precisă fac din acest instrument o alegere excelentă pentru ore și concerte.",
    stoc: 6,
    popular: true
  },
  {
    id: 7,
    nume: "Chitară Bass Fender Precision",
    categorie: "chitari",
    pret: 2100,
    pretRedus: 1800,
    rating: 4.6,
    imagine: "https://images.unsplash.com/photo-1445985543470-41fba5c3144a?w=400&h=400&fit=crop",
    descriereScurta: "Bass iconic – fundament solid pentru orice trupă.",
    descriereLunga: "Fender Precision Bass este bagheta de aur a muzicii moderne. Cu pickup-ul split single-coil și corpul din arin, oferă un sunet cald și puternic care susține orice gen muzical. Gâtul din arțar cu tastieră din paducel asigură confort la cântare.",
    stoc: 7,
    popular: false
  },
  {
    id: 8,
    nume: "Ukulele Soprano Kala KA-15S",
    categorie: "chitari",
    pret: 320,
    pretRedus: null,
    rating: 4.3,
    imagine: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRen3tWvddkuurpMiBKOr2bUpcwmdfBbxn59w&s",
    descriereScurta: "Ukulele soprano din mahon – sunet cald și portabil.",
    descriereLunga: "Kala KA-15S este unul dintre cele mai populare ukulele pentru începători. Corpul și gâtul din mahon oferă un sunet cald și rezonant. Corzile din nylon asigură confort la cântare. Perfect pentru vacanțe, plajă sau studio.",
    stoc: 20,
    popular: false
  },
  {
    id: 9,
    nume: "Clape MIDI Arturia KeyLab 49",
    categorie: "piane",
    pret: 1600,
    pretRedus: 1350,
    rating: 4.5,
    imagine: "https://images.unsplash.com/photo-1598653222000-6b7b7a552625?w=400&h=400&fit=crop",
    descriereScurta: "Controller MIDI profesional cu 49 clape semi-ponderate.",
    descriereLunga: "Arturia KeyLab 49 este controlerul MIDI ideal pentru producători și muzicieni. Cu 49 de clape semi-ponderate, 16 pad-uri, 9 fader-e și encodere rotative, oferă control complet asupra software-ului DAW preferat. Include Analog Lab cu mii de sunete.",
    stoc: 10,
    popular: true
  },
  {
    id: 10,
    nume: "Orgă Hammond SK1",
    categorie: "piane",
    pret: 5500,
    pretRedus: null,
    rating: 4.9,
    imagine: "https://c.cdnmp.net/870358742/p/l/0/orga-profesionala-electronica-mk-805-cu-61-de-clape-5-octave-citire~4160.jpg",
    descriereScurta: "Orgă stage profesională – sunetul clasic Hammond în format portabil.",
    descriereLunga: "Hammond SK1 reproduce autenticul sunet al orgilor Hammond vintage cu tehnologie modernă. Oferă 61 de clape, multiple registre de organ, drawbars digitale și o greutate redusă pentru transport ușor. Indispensabilă pentru jazz, gospel și rock.",
    stoc: 2,
    popular: true
  },
  {
    id: 11,
    nume: "Trompetă Bach Stradivarius",
    categorie: "vanturi",
    pret: 4200,
    pretRedus: null,
    rating: 4.8,
    imagine: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQoVzGbJ7nutkaoErFDZlwXqCZk958Mia4cJQ&s",
    descriereScurta: "Trompetă profesională – preferata orchestrelor din lumea întreagă.",
    descriereLunga: "Bach Stradivarius este standardul de aur în lumea trompetelor profesionale. Fabricată manual din alamă de înaltă calitate, oferă un sunet clar, puternic și bine proiectat. Folosită de soliști și orchestre din toată lumea pentru prestanța și fiabilitatea sa.",
    stoc: 4,
    popular: false
  },
  {
    id: 12,
    nume: "Tobe Electronice Roland TD-17KVX",
    categorie: "tobe",
    pret: 6800,
    pretRedus: 5900,
    rating: 4.7,
    imagine: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSXuaUTnxCM8g_58sDM0OwPeOe80uVPnXmZvw&s",
    descriereScurta: "Set tobe electronice profesional – cântă oriunde, oricând.",
    descriereLunga: "Roland TD-17KVX este setul ideal pentru bateristul modern care vrea să cânte fără restricții de volum. Pad-urile cu 2 zone oferă dinamică autentică, modulul TD-17 include sute de kituri de tobe și permite conectarea la computer sau telefon.",
    stoc: 5,
    popular: true
  },
  {
    id: 13,
    nume: "Cajon Meinl Artisan",
    categorie: "tobe",
    pret: 680,
    pretRedus: null,
    rating: 4.4,
    imagine: "https://blog.sweelee.com/uploads/2021/06/your-guide-to-buying-a-cajon-banner@1200x630-1024x538.jpg",
    descriereScurta: "Cajon handcrafted – ritm și stil într-un singur instrument.",
    descriereLunga: "Meinl Artisan Cajon este fabricat manual din lemn de mahon selectat. Placa de lovire din mesteacăn oferă un bas profund și un treble clar. Snare-urile ajustabile permit personalizarea sunetului. Ușor de transportat, perfect pentru sesiuni acustice.",
    stoc: 12,
    popular: false
  },
  {
    id: 14,
    nume: "Vioară Student 4/4",
    categorie: "vanturi",
    pret: 450,
    pretRedus: null,
    rating: 4.1,
    imagine: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcShD3Qqh6dC35ZazevVlbxGKBRJUJwP5ZItig&",
    descriereScurta: "Vioară pentru studenți – calitate bună la preț accesibil.",
    descriereLunga: "Această vioară 4/4 este perfectă pentru studenți și elevi. Corpul din lemn de molid și arțar oferă un sunet cald și rezistent. Include arcuș, colofoniu și husă rigidă de protecție. Ideal pentru primii ani de studiu al viorii.",
    stoc: 18,
    popular: false
  },
  {
    id: 15,
    nume: "Microfon Shure SM58",
    categorie: "vanturi",
    pret: 780,
    pretRedus: null,
    rating: 4.9,
    imagine: "https://www.lerato.ro/blog/wp-content/uploads/2021/09/Microfon-omnidirectional-ce-este.jpg",
    descriereScurta: "Microfonul de scenă nr. 1 în lume – robust și de încredere.",
    descriereLunga: "Shure SM58 este microfonul vocal de referință folosit pe scenele din toată lumea. Capsula cardioidă oferă o reproducere clară a vocii și respinge zgomotul de fundal. Carcasa robustă rezistă la utilizare intensă. Standardul industriei pentru voce live.",
    stoc: 25,
    popular: true
  },
  {
    id: 16,
    nume: "Chitară Clasică Cordoba C5",
    categorie: "chitari",
    pret: 1100,
    pretRedus: 950,
    rating: 4.5,
    imagine: "https://c.cdnmp.net/957566326/blog/3.jpg?rv=1742744205",
    descriereScurta: "Chitară clasică din cedru – sunet cald, ideal pentru flamenco.",
    descriereLunga: "Cordoba C5 este o chitară clasică de înaltă calitate cu față din cedru solid și spate/laterale din mahon. Corzile din nylon asigură confort la cântare și un sunet cald, specific chitarei clasice și flamenco. Include husă Gig Bag de protecție.",
    stoc: 9,
    popular: false
  }
];
